[package]
name = "yuyib-input"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Semantic keyboard action maps and Winit input adapter for Yuyib."

[dependencies]
winit.workspace = true
yuyib-gameplay = { path = "../yuyib-gameplay", version = "0.1.0" }
yuyib-platform = { path = "../yuyib-platform", version = "0.1.0" }
yuyib-physics = { path = "../yuyib-physics", version = "0.1.0" }
yuyib-render-3d = { path = "../yuyib-render-3d", version = "0.1.0" }
yuyib-ui = { path = "../yuyib-ui", version = "0.1.0" }

[lints]
workspace = true
